import express from 'express';import * as cheerio from 'cheerio';import cron from 'node-cron';import fs from 'fs';import crypto from 'crypto';
const app=express(),PORT=process.env.PORT||3000,FILE='./data.json';app.use(express.json());app.use(express.static('.'));
const initial={products:[
{id:'881421',name:'30th CELEBRATION BOX',url:'https://snkrdunk.com/apparels/881421'},
{id:'881423',name:'30th CELEBRATION プレミアムデッキセット エーフィ・ブラッキー',url:'https://snkrdunk.com/apparels/881423'},
{id:'881424',name:'30th CELEBRATION FUTURISTIC BOX',url:'https://snkrdunk.com/apparels/881424'}],history:[]};
if(!fs.existsSync(FILE))fs.writeFileSync(FILE,JSON.stringify(initial,null,2));const read=()=>JSON.parse(fs.readFileSync(FILE));const write=d=>fs.writeFileSync(FILE,JSON.stringify(d,null,2));
async function scrape(p){const r=await fetch(p.url,{headers:{'user-agent':'Mozilla/5.0 (compatible; PCGMarketChecker/1.0)'}});if(!r.ok)throw Error('HTTP '+r.status);const html=await r.text(),$=cheerio.load(html),text=$('body').text().replace(/\s+/g,' ');let name=$('h1').first().text().trim()||p.name;let m=text.match(/1個\(.*?\)\s*¥\s*([\d,]+)\s*~/);if(!m)m=text.match(/購入手数料\s*¥[\d,]+\s*¥\s*([\d,]+)\s*~/);if(!m)throw Error('1個価格を検出できません');return{name,price:+m[1].replaceAll(',','')}}
async function refresh(){const d=read(),date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());for(const p of d.products){try{const x=await scrape(p);p.name=x.name;const i=d.history.findIndex(h=>h.productId===p.id&&h.date===date);const row={productId:p.id,date,price:x.price};i>=0?d.history[i]=row:d.history.push(row)}catch(e){console.error(p.url,e.message)}}write(d)}
app.get('/api/data',(q,s)=>s.json(read()));app.post('/api/refresh',async(q,s)=>{await refresh();s.json({ok:true})});app.post('/api/products',(q,s)=>{const d=read(),url=String(q.body.url||'');if(!/^https:\/\/snkrdunk\.com\/apparels\/\d+/.test(url))return s.status(400).send('スニダンの商品URLを入力してください');d.products.push({id:crypto.randomUUID(),name:q.body.name||'新規商品',url});write(d);s.json({ok:true})});app.delete('/api/products/:id',(q,s)=>{const d=read();d.products=d.products.filter(p=>p.id!==q.params.id);d.history=d.history.filter(h=>h.productId!==q.params.id);write(d);s.json({ok:true})});
cron.schedule('7 * * * *',refresh,{timezone:'Asia/Tokyo'});app.listen(PORT,()=>console.log(`PCG相場チェッカー: http://localhost:${PORT}`));
